version: '3.8'

services:
  ani-server:
    image: ani-server
    build: .
    env_file: .env
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}

# 移除了mysql服务和volumes配置，因为现在直接使用外部MySQL服务